theme: jekyll-theme-minimal
title: UCTrees
description: Forest and landscape restoration of degraded lands and surplus croplands can play a significant role in sequestering carbon.  The UCTrees project at the [University of Cambridge Computre Laboratory](https://www.cl.cam.ac.uk) is researching how techniques from computer science can help improve current practices in forest and landscape restoration.
logo: logo.png
